{"ID": "fa9edfe9-8730-4c2d-b4f5-5900698de973", "effective_cve": "CVE-2021-26291", "image": {"exact": "docker.io/anchore/test_images@sha256:808f6cf3cf4473eb39ff9bb47ead639d2ed71255b75b9b140162b58c6102bcc9"}, "label": "??", "package": {"name": "maven-resolver-util", "version": "1.1.1"}, "timestamp": "2022-11-01T16:02:45+00:00", "tool": "grype@v0.51.0-7-gfcce63b", "user": "westonsteimel", "vulnerability_id": "CVE-2021-26291"}