{"ID": "b810962f-c38a-4c9a-94cc-3d1a2349f917", "effective_cve": "CVE-2018-1061", "image": {"exact": "docker.io/centos@sha256:3688aa867eb84332460e172b9250c9c198fdfd8d987605fd53f246f498c60bcf"}, "label": "TP", "package": {"name": "python", "version": "2.6.6-66.el6_8"}, "timestamp": "2022-09-15T18:57:12-04:00", "user": "wagoodman", "vulnerability_id": "CVE-2018-1061"}