{"ID": "d54b48b6-0850-4335-8185-a1869bd5e96a", "effective_cve": "CVE-2020-26116", "image": {"exact": "docker.io/ubuntu@sha256:881afbae521c910f764f7187dbfbca3cc10c26f8bafa458c76dda009a901c29d"}, "label": "TP", "package": {"name": "python3.4-minimal", "version": "3.4.3-1ubuntu1~14.04.7"}, "timestamp": "2024-05-16T17:14:03.757561+00:00", "tool": "grype@v0.77.4", "user": "wagoodman", "vulnerability_id": "CVE-2020-26116"}