{"ID": "393e77f2-d0c4-4fe7-a94d-b3d2b15d5e3a", "effective_cve": "CVE-2016-3518", "image": {"exact": "docker.io/anchore/test_images@sha256:f56164678054e5eb59ab838367373a49df723b324617b1ba6de775749d7f91d4"}, "label": "FP", "package": {"name": "mysql", "version": "2.18.1"}, "timestamp": "2022-09-14T17:45:53+01:00", "user": "westonsteimel", "vulnerability_id": "CVE-2016-3518"}