{"ID": "f964bf2c-21cf-4ed1-8b79-4b1804e97389", "effective_cve": "CVE-2018-3082", "image": {"exact": "docker.io/anchore/test_images@sha256:f56164678054e5eb59ab838367373a49df723b324617b1ba6de775749d7f91d4"}, "label": "FP", "package": {"name": "mysql", "version": "2.18.1"}, "timestamp": "2022-09-14T17:47:15+01:00", "user": "westonsteimel", "vulnerability_id": "CVE-2018-3082"}