{"ID": "e34e8de8-5d37-4039-b379-df8cef8fd587", "effective_cve": "CVE-2013-0340", "image": {"exact": "docker.io/anchore/test_images@sha256:ff80ae5de3446939639f3fbb58f66f641e2da1d881bdab704d9237424f64417f"}, "label": "TP", "package": {"name": "python3", "version": "3.8.10-r0"}, "timestamp": "2023-02-13T18:00:01+00:00", "tool": "grype@v0.56.0-30-g17e11ac", "user": "westonsteimel", "vulnerability_id": "CVE-2013-0340"}