{"ID": "e1bed570-6a21-427c-bc11-df8d68a7d7e3", "effective_cve": "CVE-2019-16935", "image": {"exact": "docker.io/gitlab/gitlab-ce@sha256:04d4219d5dfb3acccc9997e50477c8d24b371387a95857e1ea8fc779e17a716c"}, "label": "FP", "package": {"name": "python", "version": "0.0.0-DEVELOPMENT"}, "timestamp": "2022-12-09T20:11:36+00:00", "tool": "grype@v0.53.1", "user": "westonsteimel", "vulnerability_id": "CVE-2019-16935"}