{"ID": "3d288768-6afb-4e7a-a096-7e283d4fb1f9", "effective_cve": "CVE-2020-10735", "image": {"exact": "docker.io/cloudbees/cloudbees-core-mm@sha256:4c564f473d38f23da1caa48c4ef53b958ef03d279232007ad3319b1f38584bdb"}, "label": "TP", "package": {"name": "python3-libs", "version": "3.6.8-31.el8"}, "timestamp": "2022-09-14T16:45:26-04:00", "user": "wagoodman", "vulnerability_id": "CVE-2020-10735"}