{"ID": "c1cfe8a2-c451-4070-b7b4-60a167009049", "effective_cve": "CVE-2020-8492", "image": {"exact": "docker.io/cloudbees/cloudbees-core-oc@sha256:9cd85ee84e401dc27e3a8268aae67b594a651b2f4c7fc056ca14c7b0a0a6b82d"}, "label": "TP", "package": {"name": "libpython2.7-stdlib", "version": "2.7.16-2+deb10u1"}, "timestamp": "2023-01-26T16:04:45+00:00", "tool": "grype@v0.55.0-24-gc01ee9b", "user": "westonsteimel", "vulnerability_id": "CVE-2020-8492"}