{"ID": "c5bc17f3-3666-4efd-bfa2-7277c287e62f", "effective_cve": "CVE-2019-8457", "image": {"exact": "docker.io/python@sha256:5e96e03a493a54904aa8be573fc0414431afb4f47ac58fbffd03b2a725005364"}, "label": "TP", "package": {"name": "libdb5.3", "version": "5.3.28+dfsg1-0.5"}, "timestamp": "2022-09-29T22:06:50+01:00", "tool": "grype@34e08a0", "user": "westonsteimel", "vulnerability_id": "CVE-2019-8457"}